{% set name = "taskflow" %}
{% set version = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/taskflow/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: fe86765da417f6ceaa2d232ffac70c9afaeb3dc0816337d39a7c93e39c2dee0b

build:
  number: 1
  skip: true  # [win and vc<14]
  skip: true  # [cuda_compiler_version == "11.8"]
  string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  string: cuda{{ cuda_compiler_version | replace('.', '') }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - {{ stdlib("c") }}
    - cmake
    - make
    - ninja  # [not win]
  host:
    - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
    - cuda-toolkit                              # [cuda_compiler_version != "None"]
  run:
    - cuda-cudart  # [cuda_compiler_version != "None"]

test:
  commands:
    - test -d ${PREFIX}/include/taskflow  # [unix]
    - test -f ${PREFIX}/include/taskflow/taskflow.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/Taskflow/TaskflowConfig.cmake  # [osx]
    - test -f ${PREFIX}/lib/cmake/Taskflow/TaskflowConfigVersion.cmake  # [osx]
    - test -f ${PREFIX}/lib/cmake/Taskflow/TaskflowConfig.cmake  # [linux]
    - test -f ${PREFIX}/lib/cmake/Taskflow/TaskflowConfigVersion.cmake  # [linux]
    - if not exist %LIBRARY_PREFIX%\include\taskflow\taskflow.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\Taskflow\TaskflowConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\Taskflow\TaskflowConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/taskflow/taskflow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Parallel and Heterogeneous Task Programming in Modern C++
  doc_url: https://taskflow.github.io/taskflow/index.html
  dev_url: https://github.com/taskflow/taskflow

extra:
  recipe-maintainers:
    - jeongseok-meta
    - davidbrochart
