{% set name = "taskflow" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/taskflow/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0a9e0f700e7750834f717d7523660399ff7ec455e51000009b3e17923c26b80d

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - ninja  # [not win]

test:
  commands:
    - test -d ${PREFIX}/include/taskflow  # [unix]
    - test -f ${PREFIX}/include/taskflow/taskflow.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/Taskflow/TaskflowConfig.cmake  # [osx]
    - test -f ${PREFIX}/lib/cmake/Taskflow/TaskflowConfigVersion.cmake  # [osx]
    - test -f ${PREFIX}/lib/cmake/Taskflow/TaskflowConfig.cmake  # [linux]
    - test -f ${PREFIX}/lib/cmake/Taskflow/TaskflowConfigVersion.cmake  # [linux]
    - if not exist %LIBRARY_PREFIX%\include\taskflow\taskflow.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\Taskflow\TaskflowConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\lib\cmake\Taskflow\TaskflowConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/taskflow/taskflow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Parallel and Heterogeneous Task Programming in Modern C++
  doc_url: https://taskflow.github.io/taskflow/index.html
  dev_url: https://github.com/taskflow/taskflow

extra:
  recipe-maintainers:
    - jeongseok-meta
    - davidbrochart
